"""Contract export (SPEC §4, §11.2 items 2 and 3)."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from datetime import timedelta
from pathlib import Path
from typing import Annotated, Literal

import pytest
from pydantic import Field, SecretStr
from pydantic_settings import BaseSettings, NoDecode, SettingsConfigDict

import docuconf
from docuconf import Csv, DeclarationError, Keystore, KeystoreFile, TextFile, cli
from docuconf.durations import format_go_duration, parse_go_duration, to_go
from tests.conftest import find_cue
from tests.fixtures.sample_settings import GatewaySettings

HERE = Path(__file__).parent
GOLDEN = HERE / "golden/sample_gateway.cue"
SPEC_CUE = Path(os.environ.get("DOCUCONF_SPEC_CUE", HERE.parent.parent / "docuconf-go/spec/cue"))
CUE = find_cue()
CAN_VET = CUE is not None and (SPEC_CUE / "cue.mod").is_dir() and (SPEC_CUE / "contract").is_dir()
needs_cue = pytest.mark.skipif(not CAN_VET, reason="cue or the docuconf-go meta-schema is not available")


def vet(contract: str, tmp_path: Path) -> subprocess.CompletedProcess[str]:
    """Copy the meta-schema module to a temp dir and vet ``contract`` as package ./svc."""
    shutil.copytree(SPEC_CUE / "cue.mod", tmp_path / "cue.mod")
    shutil.copytree(SPEC_CUE / "contract", tmp_path / "contract")
    (tmp_path / "svc").mkdir()
    (tmp_path / "svc/contract.cue").write_text(contract)
    assert CUE is not None
    return subprocess.run([CUE, "vet", "-c", "./svc"], cwd=tmp_path, capture_output=True, text=True)


@pytest.mark.skipif(os.environ.get("DOCUCONF_REQUIRE_VET") != "1", reason="only in CI")
def test_cue_is_available() -> None:
    assert CUE is not None, "cue binary"
    assert (SPEC_CUE / "contract").is_dir(), f"meta-schema at {SPEC_CUE}"


def test_golden() -> None:
    out = docuconf.to_contract(GatewaySettings)
    if os.environ.get("UPDATE_GOLDEN") == "1":
        GOLDEN.parent.mkdir(exist_ok=True)
        GOLDEN.write_text(out)
    assert out == GOLDEN.read_text()
    assert docuconf.declaration(GatewaySettings).warnings == []


def test_deterministic() -> None:
    assert docuconf.to_contract(GatewaySettings) == docuconf.to_contract(GatewaySettings)
    data = docuconf.contract_data(GatewaySettings)
    assert list(data["vars"]) == sorted(data["vars"])
    assert list(data["files"]) == sorted(data["files"])


def test_header_and_metadata() -> None:
    out = docuconf.to_contract(GatewaySettings, name="gw", app_version="1.2.3")
    lines = out.splitlines()
    assert lines[:4] == [
        "// Code generated by docuconf. DO NOT EDIT.",
        "package gw",
        "",
        'import "docuconf.dev/contract"',
    ]
    assert "contract.#Contract & {" in out
    data = docuconf.contract_data(GatewaySettings, app_version="abc123")
    assert data["metadata"]["appVersion"] == "abc123"
    assert data["metadata"]["generator"] == {
        "language": "python",
        "sdk": "docuconf-pydantic",
        "version": docuconf.__version__,
    }


@needs_cue
def test_golden_passes_cue_vet(tmp_path: Path) -> None:
    r = vet(docuconf.to_contract(GatewaySettings), tmp_path)
    assert r.returncode == 0, r.stdout + r.stderr


@needs_cue
def test_export_matches_data_after_cue_export(tmp_path: Path) -> None:
    """The CUE text and contract_data() agree (cue export to JSON)."""
    r = vet(docuconf.to_contract(GatewaySettings), tmp_path)
    assert r.returncode == 0
    assert CUE is not None
    exported = subprocess.run(
        [CUE, "export", "./svc", "--out", "json"], cwd=tmp_path, capture_output=True, text=True, check=True
    )
    got = json.loads(exported.stdout)
    want = docuconf.contract_data(GatewaySettings)
    assert got["vars"]["PORT"] == {**want["vars"]["PORT"], "required": False, "secret": False, "name": "PORT"}
    assert got["files"]["routes"]["schema"] == want["files"]["routes"]["schema"]


@needs_cue
def test_meta_schema_rejects_a_broken_contract(tmp_path: Path) -> None:
    broken = docuconf.to_contract(GatewaySettings).replace('"HTTP listen port"', '"port"')
    assert vet(broken, tmp_path).returncode != 0


def test_cli_export(tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]) -> None:
    monkeypatch.chdir(HERE.parent)
    out = tmp_path / "contract.cue"
    assert cli.main(["export", "tests.fixtures.sample_settings:GatewaySettings", "--out", str(out)]) == 0
    assert out.read_text() == GOLDEN.read_text()
    assert cli.main(["export", "tests.fixtures.sample_settings:GatewaySettings", "--out", str(out), "--check"]) == 0
    out.write_text("stale")
    assert cli.main(["export", "tests.fixtures.sample_settings:GatewaySettings", "--out", str(out), "--check"]) == 1
    assert cli.main(["export", "tests.fixtures.sample_settings:GatewaySettings", "--name", "other"]) == 0
    assert 'name: "other"' in capsys.readouterr().out


def test_console_script(tmp_path: Path) -> None:
    exe = Path(sys.executable).parent / "docuconf"
    if not exe.exists():
        pytest.skip("console script not installed")
    r = subprocess.run(
        [str(exe), "export", "tests.fixtures.sample_settings:GatewaySettings"],
        cwd=HERE.parent,
        capture_output=True,
        text=True,
    )
    assert r.returncode == 0, r.stderr
    assert r.stdout == GOLDEN.read_text()


def problems(cls: type[BaseSettings]) -> str:
    docuconf.declaration.__globals__["_cache"].pop(cls, None)  # type: ignore[attr-defined]
    with pytest.raises(DeclarationError) as info:
        docuconf.to_contract(cls, name="svc")
    return str(info.value)


def test_declaration_errors() -> None:
    class S(BaseSettings):
        # pydantic's default Rust engine already rejects lookaround; python-re does not.
        model_config = SettingsConfigDict(env_prefix="APP_", regex_engine="python-re")
        short: str = Field(description="tiny")
        nodesc: int = 3
        look: str = Field("abc", description="Lookahead pattern", pattern=r"^(?=a)\w+$")
        backref: str = Field("aa", description="Backreference pattern", pattern=r"(a)\1")
        bad_default: int = Field(0, description="Default out of range", ge=1)
        secret_default: SecretStr = Field(SecretStr("x"), description="Secret with a default")
        csv_only: Annotated[list[str], Csv()] = Field(default_factory=list, description="Csv without NoDecode")
        ints: Literal[1, 2] = Field(1, description="Literal of ints")
        ks: Annotated[Keystore, KeystoreFile(path="/etc/app/ks/ks.p12", password_var="APP_SHORT")] = Field(
            description="Keystore with a non-secret password var"
        )
        lic: Annotated[str, TextFile(path="relative/license.key")] = Field(description="Licence file")

    msg = problems(S)
    for needle in (
        "APP_SHORT (short): needs a description",
        "APP_NODESC (nodesc): needs a description",
        "lookahead",
        "backreference",
        "APP_BAD_DEFAULT (bad_default): default 0 does not satisfy",
        "a secret must not have a default",
        "docuconf.Csv needs NoDecode",
        "enum values must be strings",
        "password_var APP_SHORT must name a declared secret variable",
        "path 'relative/license.key' must be absolute",
    ):
        assert needle in msg, needle


def test_name_rules() -> None:
    class S(BaseSettings):
        model_config = SettingsConfigDict(case_sensitive=True)
        port: int = Field(8080, description="HTTP listen port")

    assert "env name must match" in problems(S)

    class Ok(BaseSettings):
        port: int = Field(8080, description="HTTP listen port")

    with pytest.raises(DeclarationError):
        docuconf.to_contract(Ok, name="Not_A_Label")


def test_path_env_must_not_be_a_var() -> None:
    class S(BaseSettings):
        lic: Annotated[str, TextFile(path="/etc/app/lic/license.key", path_env="LICENSE_FILE")] = Field(
            description="Licence file"
        )
        license_file: str = Field("x", description="Clashes with pathEnv")

    assert "pathEnv LICENSE_FILE must not also be a declared variable" in problems(S)


def test_warnings() -> None:
    class S(BaseSettings):
        enable_checkout: bool = Field(False, description="Deploy-time kill switch")
        hosts: Annotated[list[str], NoDecode] = Field(default_factory=list, description="Hosts, split by a validator")
        ratio: float = Field(0.5, description="Exclusive bound", gt=0)

    warnings = docuconf.declaration(S).warnings
    assert any("ENABLE_CHECKOUT: looks like a feature flag" in w for w in warnings)
    assert any("NoDecode without docuconf.Csv" in w for w in warnings)
    assert any("gt is exported as an inclusive min" in w for w in warnings)


def test_deprecated_and_examples() -> None:
    class S(BaseSettings):
        db_url: str = Field(
            "postgres://x",
            description="Old database URL",
            deprecated="use DATABASE_URL",
            json_schema_extra=None,
        )
        tags: list[str] = Field(default_factory=lambda: ["a"], description="Tags for metrics", examples=[["a", "b"]])

    data = docuconf.contract_data(S, name="svc")
    assert data["vars"]["DB_URL"]["deprecated"] == {"message": "use DATABASE_URL"}
    assert data["vars"]["TAGS"]["default"] == ["a"]


def test_durations() -> None:
    assert to_go(timedelta(minutes=90)) == "1h30m"
    assert to_go("90m") == "1h30m"
    assert to_go(timedelta(milliseconds=1500)) == "1s500ms"
    assert to_go(timedelta(0)) == "0s"
    assert parse_go_duration("1.5h") == 5400 * 10**9
    assert format_go_duration(parse_go_duration("2h45m30s")) == "2h45m30s"
    with pytest.raises(ValueError):
        parse_go_duration("5 minutes")


def test_readme_example(tmp_path: Path) -> None:
    from examples.app.settings import Settings

    out = docuconf.to_contract(Settings)
    assert out == (HERE.parent / "examples/app/contract.cue").read_text()
    if CAN_VET:
        r = vet(out, tmp_path)
        assert r.returncode == 0, r.stdout + r.stderr
