"""Contract export (SPEC §4, §11.2 item 3)."""

from __future__ import annotations

import re
from typing import Any

from pydantic_settings import BaseSettings

from . import cue
from ._version import __version__
from .declaration import SERVICE_NAME, declaration
from .errors import DeclarationError

SDK_NAME = "docuconf-pydantic"
HEADER = "// Code generated by docuconf. DO NOT EDIT."


def contract_data(
    cls: type[BaseSettings], *, name: str | None = None, app_version: str | None = None
) -> dict[str, Any]:
    """The contract as plain data (what ``cue export`` would produce)."""
    decl = declaration(cls)
    service = name or decl.service
    if not service:
        raise DeclarationError(
            [
                f"{cls.__name__} has no service name (a class named just Settings has none of its own); pass name= "
                f'or set docuconf_service: ClassVar[str] = "my-service" on the settings class'
            ]
        )
    if not SERVICE_NAME.match(service):
        raise DeclarationError(
            [
                f"service name {service!r} must be a DNS label (lower case, digits and -); pass name= or set "
                "docuconf_service: ClassVar[str] on the settings class"
            ]
        )
    metadata: dict[str, Any] = {"name": service}
    if app_version:
        metadata["appVersion"] = app_version
    metadata["generator"] = {"language": "python", "sdk": SDK_NAME, "version": __version__}
    out: dict[str, Any] = {
        "apiVersion": "docuconf.dev/v1alpha1",
        "kind": "ConfigContract",
        "metadata": metadata,
        "vars": {v.name: v.contract() for v in decl.vars},
    }
    if decl.files:
        out["files"] = {f.name: f.contract() for f in decl.files}
    if decl.overlays:
        out["overlays"] = {o.name: o.contract() for o in sorted(decl.overlays, key=lambda o: o.name)}
    return out


def package_name(service: str) -> str:
    pkg = re.sub(r"[^A-Za-z0-9_]", "_", service)
    return pkg if re.match(r"^[A-Za-z]", pkg) else f"svc_{pkg}"


def to_contract(cls: type[BaseSettings], *, name: str | None = None, app_version: str | None = None) -> str:
    """Export ``cls`` as a ``contract.cue`` document.

    Deterministic: variables, file inputs and overlays are sorted by name.
    """
    data = contract_data(cls, name=name, app_version=app_version)
    body = cue.fields(list(data.items()), "\t")
    return (
        f"{HEADER}\npackage {package_name(data['metadata']['name'])}\n\n"
        f'import "docuconf.dev/contract"\n\ncontract.#Contract & {{\n{body}\n}}\n'
    )


def export_warnings(cls: type[BaseSettings]) -> list[str]:
    return list(declaration(cls).warnings)
