// Code generated by docuconf. DO NOT EDIT.
package sample_gateway

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "sample-gateway"
		generator: {
			language: "python"
			sdk:      "docuconf-pydantic"
			version:  "0.1.0"
		}
	}
	vars: {
		ALLOWED_ORIGINS: {
			type:        "list"
			description: "CORS origins allowed to call the API"
			required:    true
			items:       "string"
			encoding:    "csv"
			separator:   ","
			minItems:    1
			maxItems:    10
		}
		DATABASE_URL: {
			type:        "url"
			description: "Primary Postgres connection string"
			required:    true
			secret:      true
			schemes: ["postgres", "postgresql"]
		}
		DEBUG: {
			type:        "bool"
			description: "Verbose request logging"
			default:     false
		}
		GOMEMLIMIT: {
			type:        "int"
			description: "Soft memory limit, in bytes"
			min:         1
		}
		KEYSTORE_PASSWORD: {
			type:        "string"
			description: "Password for the partner keystore"
			required:    true
			secret:      true
			minLength:   1
		}
		LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level emitted"
			group:       "logging"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		MODE: {
			type:        "enum"
			description: "Replication role of this instance"
			values: ["active", "standby"]
			default: "active"
		}
		PORT: {
			type:        "int"
			description: "HTTP listen port"
			min:         1
			max:         65535
			default:     8080
		}
		PUBLIC_URL: {
			type:        "url"
			description: "Externally visible base URL"
			required:    true
			schemes: ["https"]
		}
		RATE_LIMITS: {
			type:        "json"
			description: "Default per-client rate limits"
			schema: {
				additionalProperties: false
				properties: {
					perMinute: {
						minimum: 1
						title:   "Perminute"
						type:    "integer"
					}
					burst: {
						default: 0
						minimum: 0
						title:   "Burst"
						type:    "integer"
					}
				}
				required: ["perMinute"]
				title: "RateLimits"
				type:  "object"
			}
		}
		REGION: {
			type:        "string"
			description: "Cloud region the service runs in"
			required:    true
			examples: ["eu-west-1"]
			minLength: 4
			maxLength: 32
			pattern:   "^[a-z]{2}-[a-z]+-[0-9]$"
		}
		REPLICA_DSN: {
			type:        "url"
			description: "Read replica connection string"
			schemes: ["postgres", "postgresql", "postgresql+asyncpg", "postgresql+pg8000", "postgresql+psycopg", "postgresql+psycopg2", "postgresql+psycopg2cffi", "postgresql+py-postgresql", "postgresql+pygresql"]
		}
		REQUEST_TIMEOUT: {
			type:        "duration"
			description: "Upstream request timeout"
			encoding:    "iso8601"
			min:         "1s"
			max:         "5m"
			default:     "30s"
		}
		SAMPLE_RATE: {
			type:        "float"
			description: "Fraction of requests traced"
			min:         0
			max:         1
			default:     0.25
		}
		WORKER_PORTS: {
			type:        "list"
			description: "Ports the workers bind"
			items:       "int"
			encoding:    "json"
			default: []
		}
	}
	files: {
		geoip: {
			type:        "binary"
			description: "GeoIP database for country-based routing"
			path:        "/data/geoip/GeoLite2-City.mmdb"
			maxSize:     134217728
		}
		license: {
			type:        "text"
			description: "Gateway licence key"
			required:    true
			path:        "/etc/gateway/license/license.key"
			pattern:     "^[A-Z0-9]{5}(-[A-Z0-9]{5}){3}\\n?$"
		}
		"partner-keystore": {
			type:        "keystore"
			format:      "pkcs12"
			description: "Client certificate for mTLS to the partner API"
			secret:      true
			path:        "/etc/gateway/partner/keystore.p12"
			passwordVar: "KEYSTORE_PASSWORD"
		}
		routes: {
			type:        "config"
			format:      "yaml"
			description: "Routing table: path prefixes and their upstreams"
			required:    true
			path:        "/etc/gateway/routes/routes.yaml"
			pathEnv:     "ROUTES_FILE"
			reload:      "watch"
			maxSize:     65536
			schema: {
				"$defs": {
					Route: {
						additionalProperties: false
						properties: {
							match: {
								pattern: "^/"
								title:   "Match"
								type:    "string"
							}
							upstream: {
								pattern: "^https?://"
								title:   "Upstream"
								type:    "string"
							}
							timeout: {
								anyOf: [
									{
										type: "string"
									},
									{
										type: "null"
									},
								]
								default: null
								title:   "Timeout"
							}
						}
						required: ["match", "upstream"]
						title: "Route"
						type:  "object"
					}
				}
				additionalProperties: false
				properties: {
					routes: {
						items: {
							"$ref": "#/$defs/Route"
						}
						minItems: 1
						title:    "Routes"
						type:     "array"
					}
				}
				required: ["routes"]
				title: "Routes"
				type:  "object"
			}
		}
		"serving-tls": {
			type:        "tls"
			description: "Certificate the gateway serves HTTPS with"
			required:    true
			secret:      true
			path:        "/etc/gateway/tls"
			reload:      "watch"
			dnsNames: ["gateway.internal", "api.example.com"]
			keyAlgorithms: ["ECDSA", "RSA"]
			minRemaining: "720h"
			requireCA:    true
		}
		"upstream-ca": {
			type:        "caBundle"
			description: "Private CAs the gateway trusts for upstream TLS"
			path:        "/etc/gateway/ca/bundle.pem"
			pathEnv:     "SSL_CERT_FILE"
		}
	}
}
