// Code generated by docuconf. DO NOT EDIT.
package orders

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "orders"
		generator: {
			language: "python"
			sdk:      "docuconf-pydantic"
			version:  "0.1.0"
		}
	}
	vars: {
		ORDERS_ALLOWED_ORIGINS: {
			type:        "list"
			description: "CORS origins allowed to call the API"
			items:       "string"
			encoding:    "csv"
			separator:   ","
			default: []
		}
		ORDERS_API_TOKEN: {
			type:        "string"
			description: "Token for the payments API"
			required:    true
			secret:      true
			minLength:   20
		}
		ORDERS_DATABASE_URL: {
			type:        "url"
			description: "Primary Postgres connection string"
			required:    true
			secret:      true
			schemes: ["postgres", "postgresql"]
		}
		ORDERS_LOG_LEVEL: {
			type:        "enum"
			description: "Minimum log level"
			values: ["debug", "info", "warn", "error"]
			default: "info"
		}
		ORDERS_PORT: {
			type:        "int"
			description: "HTTP listen port"
			min:         1
			max:         65535
			default:     8080
		}
		ORDERS_TIMEOUT: {
			type:        "duration"
			description: "Upstream timeout"
			encoding:    "iso8601"
			max:         "5m"
			default:     "30s"
		}
	}
	files: {
		rates: {
			type:        "config"
			format:      "json"
			description: "Per-client rate limits"
			required:    true
			path:        "/etc/orders/rates/rates.json"
			pathEnv:     "ORDERS_RATES_FILE"
			schema: {
				properties: {
					per_minute: {
						minimum: 1
						title:   "Per Minute"
						type:    "integer"
					}
					burst: {
						default: 0
						minimum: 0
						title:   "Burst"
						type:    "integer"
					}
				}
				required: ["per_minute"]
				title: "Rates"
				type:  "object"
			}
		}
		tls: {
			type:        "tls"
			description: "Certificate the service serves HTTPS with"
			required:    true
			secret:      true
			path:        "/etc/orders/tls"
			reload:      "watch"
			dnsNames: ["orders.internal"]
			minRemaining: "720h"
		}
	}
}
